version: '3.8'

services:
  locify-backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: locify-engine
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Ensure SpotDL can work inside the container (might need python installed in the node image)
    volumes:
      - ./media:/media # Or point this to the bind-mounted HDD on the host
      - ./backend/prisma/dev.db:/app/prisma/dev.db # SQLite persistent storage
    cpus: "2.0"
    mem_limit: 2g
